### ISSUE TITLE
How to use this package with Jetson-Nano-Ubuntu-20-image

### ISSUE THREAD

**Issue by srevandro** [Qengineering/TensorFlow_Lite_Segmentation_Jetson-Nano#5]
Hello, 

First of all, thank you very much for all your support in Jetson Nano and AI algorithms.

I have installed your Jetson-Nano-Ubuntu-20-image (9Gb image) on my Jetson Nano. I tried to run this algorithm (Tensorflow_lite_segmentation_Jetson-Nano) on this image, but I have a few problems.

First of all, considering the Ubuntu image has already installed tensorflow, opencv, etc. I am a little bit confused about what should I install in this image. Should I install all TensorFlow Lite frameworks (https://qengineering.eu/install-tensorflow-2-lite-on-jetson-nano.html) ?

I have tried the step above, but I get an invalid ld reference to -ltensorflow. 

If I do not install the tensorflow lite framework, and use the one install with Ubuntu image, I have errors related to missing files and references, such as builtin_op_data.h. This file is really not found on tensorflow installed with the Ubuntu image. What should I do?

Please, if you can help me on that, I really appreciate your support. 

Thanks.

**Comment by Qengineering** [comment]
@srevandro ,

I've checked one and another.

- Best you install the TensorFlow Lite framework according to our guide on your Ubuntu 20 Jetson Nano.
- Also the flatbuffers.
- Install Code::Blocks as the project hasn't a CMake.txt file (yet).  `sudo apt-get install codeblocks`
- Download the example. `git clone https://github.com/Qengineering/TensorFlow_Lite_Segmentation_Jetson-Nano.git`
- Make sure you have the downloaded TensorFlow directory renamed `tensorflow`. Otherwise you get missing header errors.
- Remove the `/home/jetson/tensorflow/bazel-bin/tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so` from the linkage, as we don't use the delegates. It can be done with an text editor in the TestUnet.cbp file before opening the project.
On my machine it compiles and played the video.

**Comment by srevandro** [comment]
> * missing

@Qengineering 

Thanks for your reply. 

I have done everything you told me. But, the only problem that I have doing this for Ubuntu 18.04/20.04, is the following message in Code:Blocks build messages:

```
File: ld
Message: cannot find -ltensorflow-lite / error: ld returned 1 exit status.
```

I have installed the tensorflow in the following directory:
/home/jetson/evandro/app/tensorflow

Do you have any idea how to solve this problem? I have seen some issues on Google, but I am not pretty sure it should work on Jetson Nano. 

Thanks again for all your help.

**Comment by srevandro** [comment]
@Qengineering 

I found the problem. In the Properties->Project Build Options->linker settings->Link libraries, you have inserted the libs directly:
- libtensorflow-lite.a
- libflatbuffers.a

I just found these 2 libs in the tensorflow directory and inserted the full path to them:
/home/jetson/evandro/app/tensorflow/tensorflow/lite/tools/make/gen/linux_aarch64/lib/libtensorflow-lite.a
/home/jetson/evandro/app/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/build/libflatbuffers.a

YOU ARE THE BEST, MAN! Really thank you for all the support. 

After experimentation with this Segmentation algorithm, I will move forward with the others algorithms on your GitHub. 

Thanks.
